from __future__ import annotations

import os
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent

# Database
DATABASE_PATH = Path(os.getenv("EARTHQUAKE_DB_PATH", BASE_DIR / "earthquakes.duckdb"))
DUCKDB_EXTENSIONS = tuple(
    ext.strip()
    for ext in os.getenv("EARTHQUAKE_DUCKDB_EXTENSIONS", "spatial").split(",")
    if ext.strip()
)

# Default query windows
DEFAULT_QUERY_HOURS = int(os.getenv("EARTHQUAKE_DEFAULT_QUERY_HOURS", "48"))
DEFAULT_NEAREST_LOOKBACK_HOURS = int(
    os.getenv("EARTHQUAKE_DEFAULT_NEAREST_LOOKBACK_HOURS", str(24 * 30))
)
DEFAULT_TIMELINE_LIMIT = int(os.getenv("EARTHQUAKE_DEFAULT_TIMELINE_LIMIT", "2000"))

# GIS defaults
DEFAULT_CLUSTER_CELL_KM = float(os.getenv("EARTHQUAKE_DEFAULT_CLUSTER_CELL_KM", "50"))
DEFAULT_BUFFER_RADIUS_KM = float(os.getenv("EARTHQUAKE_DEFAULT_BUFFER_RADIUS_KM", "200"))

# Planning placeholders for upcoming MVP steps
DEFAULT_HISTORY_IMPORT_YEARS = int(os.getenv("EARTHQUAKE_DEFAULT_HISTORY_IMPORT_YEARS", "3"))
DEFAULT_HISTORY_IMPORT_SOURCE_PATH = Path(
    os.getenv("EARTHQUAKE_DEFAULT_HISTORY_IMPORT_SOURCE_PATH", BASE_DIR / "earthquakes.csv")
)
DEFAULT_HISTORY_IMPORT_SOURCE_TYPE = os.getenv(
    "EARTHQUAKE_DEFAULT_HISTORY_IMPORT_SOURCE_TYPE", "usgs"
)
DEFAULT_HISTORY_IMPORT_SOURCE_NAME = os.getenv(
    "EARTHQUAKE_DEFAULT_HISTORY_IMPORT_SOURCE_NAME", "usgs"
)
DEFAULT_HISTORY_IMPORT_BATCH_SIZE = int(
    os.getenv("EARTHQUAKE_DEFAULT_HISTORY_IMPORT_BATCH_SIZE", "500")
)
USGS_EVENT_QUERY_URL = os.getenv(
    "EARTHQUAKE_USGS_EVENT_QUERY_URL",
    "https://earthquake.usgs.gov/fdsnws/event/1/query",
)
USGS_DEFAULT_MIN_MAGNITUDE = float(
    os.getenv("EARTHQUAKE_USGS_DEFAULT_MIN_MAGNITUDE", "4.5")
)
USGS_DEFAULT_CHUNK_DAYS = int(
    os.getenv("EARTHQUAKE_USGS_DEFAULT_CHUNK_DAYS", "30")
)
USGS_DEFAULT_REQUEST_TIMEOUT = int(
    os.getenv("EARTHQUAKE_USGS_DEFAULT_REQUEST_TIMEOUT", "30")
)
USGS_DEFAULT_MAX_RETRIES = int(
    os.getenv("EARTHQUAKE_USGS_DEFAULT_MAX_RETRIES", "3")
)

# Feature engineering defaults
DEFAULT_FEATURE_RECENT_WINDOW_HOURS = int(
    os.getenv("EARTHQUAKE_DEFAULT_FEATURE_RECENT_WINDOW_HOURS", str(24 * 7))
)
DEFAULT_FEATURE_BASELINE_YEARS = int(
    os.getenv("EARTHQUAKE_DEFAULT_FEATURE_BASELINE_YEARS", "3")
)
DEFAULT_FEATURE_BATCH_LIMIT = int(
    os.getenv("EARTHQUAKE_DEFAULT_FEATURE_BATCH_LIMIT", "500")
)
FEATURE_SCHEMA_VERSION = os.getenv("EARTHQUAKE_FEATURE_SCHEMA_VERSION", "v1")
DEFAULT_RISK_QUERY_LIMIT = int(os.getenv("EARTHQUAKE_DEFAULT_RISK_QUERY_LIMIT", "20"))

# Risk scoring placeholders for future analytics work
RISK_WEIGHT_MAGNITUDE = float(os.getenv("EARTHQUAKE_RISK_WEIGHT_MAGNITUDE", "0.4"))
RISK_WEIGHT_DEPTH = float(os.getenv("EARTHQUAKE_RISK_WEIGHT_DEPTH", "0.2"))
RISK_WEIGHT_ACTIVITY = float(os.getenv("EARTHQUAKE_RISK_WEIGHT_ACTIVITY", "0.2"))
RISK_WEIGHT_ANOMALY = float(os.getenv("EARTHQUAKE_RISK_WEIGHT_ANOMALY", "0.2"))
RISK_LEVEL_HIGH_THRESHOLD = float(os.getenv("EARTHQUAKE_RISK_LEVEL_HIGH_THRESHOLD", "65"))
RISK_LEVEL_MEDIUM_THRESHOLD = float(os.getenv("EARTHQUAKE_RISK_LEVEL_MEDIUM_THRESHOLD", "40"))
RISK_SCHEMA_VERSION = os.getenv("EARTHQUAKE_RISK_SCHEMA_VERSION", "v1")
